"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var Shape_1 = require("./Shape");
var shape = new Shape_1.Shape(1, 2);
var circle = new Circle_1.Circle(2, 2, 5);
var rectangle = new Rectangle_1.Rectangle(3, 3, 8, 5);
console.log(shape.getInfo());
console.log(circle.getInfo());
console.log(rectangle.getInfo());
